// packages/core/src/components/dropdown/DropdownComponent.tsx
import { observer } from "mobx-react";
import * as React from "react";

import { SelectOption } from "../../boxes/SelectOption";
import { EVENT_LOG, PiLogger } from "../../util/PiLogging";
import * as Keys from "../../util/Keys";
import { DropdownItem } from "./DropdownItem";

const styles = require("../styles/DropdownComponent.scss");
const LOGGER = new PiLogger("DropdownComponent");

export type DropdownProps = {
    // Called when option is selected
    handleSelectedOption: (optionId: string) => void;
    selectedOptionId: string;
    getOptions: () => SelectOption[];
    setSelectedOption: (id: string) => void;
    styleClasses: string[];
    className?: string;
};

@observer
export class DropdownComponent extends React.Component<DropdownProps, {}> {
    private element: HTMLDivElement;
    private setElement = (element: HTMLDivElement | null) => {
        if (element) {
            this.element = element;
        }
    };

    constructor(props: DropdownProps) {
        super(props);
        if (this.props.selectedOptionId === "") {
            this.initOption();
        }
        LOGGER.info(this, "constructor");
    }

    private initOption() {
        const options = this.props.getOptions();
        if (options.length > 0) {
            this.props.setSelectedOption(options[0].id);
        }
    }
    render() {
        LOGGER.info(this, "render");
        return (
            <div className={styles.dropdown}>
                <div ref={this.setElement} tabIndex={0} onKeyUp={this.onKeyUp} onKeyPress={this.onKeyUp} />
                <div className={styles.popupWrapper}>{this.renderDropdownOptions()}</div>
            </div>
        );
    }

    private renderDropdownOption = (option: SelectOption, index: number) => {
        const isSelected = option.id === this.props.selectedOptionId;
        return (
            <div key={option.id}>
                <DropdownItem onClick={this.selectOption} option={option} selected={isSelected} />
            </div>
        );
    };

    private renderDropdownOptions() {
        return <div className={styles.popup}>{this.props.getOptions().map(this.renderDropdownOption)}</div>;
    }

    /** Supports Arrow up and down keys, Enter for selection
     * Escape is forwarded to owning component, so it may use it to close the dropdown.
     *
     * NB: Called by owning component to forward key event !!
     * @param {React.KeyboardEvent<any>} e
     * @returns {boolean}
     */
    handleKeyDown(e: React.KeyboardEvent<any>): boolean {
        LOGGER.info(this, "handleKeyDown " + e.key);
        const options = this.props.getOptions();
        const index = options.findIndex(o => o.id === this.props.selectedOptionId);
        switch (e.keyCode) {
            case Keys.ARROW_DOWN:
                if (index + 1 < options.length) {
                    this.props.setSelectedOption(options[index + 1].id);
                }
                return true;
            case Keys.ARROW_UP:
                if (index > 0) {
                    this.props.setSelectedOption(options[index - 1].id);
                }
                return true;
            case Keys.ENTER:
                if (index >= 0 && index < options.length) {
                    this.props.handleSelectedOption(options[index].id);
                    this.initOption();
                    return true;
                } else {
                    return false;
                }
            case Keys.ESCAPE:
                this.props.handleSelectedOption("ESCAPE");
                this.initOption();
                return true;
        }
        return false;
    }

    private onKeyUp = (e: React.KeyboardEvent<any>) => {
        EVENT_LOG.info(this, "onKeyUp: " + e.key);
        if (e.keyCode === Keys.ESCAPE) {
            e.preventDefault();
            e.stopPropagation();
        }
    };

    private selectOption = (option: SelectOption): void => {
        LOGGER.info(this, "selectOption " + JSON.stringify(option));
        if (option && option.label !== undefined) {
            this.props.handleSelectedOption(option.id);
        }
    };
}

// packages/core-svelte/src/components/DropdownComponent.svelte
<script lang="ts">
    import { clickOutside } from "./clickOutside"
    import { autorun } from "mobx";
    import { createEventDispatcher } from "svelte";
    import { findOption } from "../boxes/SvelteSelectOption";
    import DropdownItemComponent from "./DropdownItemComponent.svelte";
    import type { SelectOption } from "@projectit/core";
    import {
        ARROW_LEFT,
        ARROW_DOWN,
        ARROW_UP,
        ARROW_RIGHT,
        ENTER,
        DELETE,
        ESCAPE,
        PiLogger
    } from "@projectit/core";

    export let getOptions: () => SelectOption[];
    export let selectedOptionId: string = "1";
    export let open: boolean;
    export let handleSelectedOption: (option: SelectOption) => void;

    const LOGGER = new PiLogger("DropdownComponent");

    const getOptionsLogged = (): SelectOption[] => {
        const options = getOptions();
        LOGGER.log("getOptions");
        options.forEach(o => LOGGER.log("     Option ["+ o.id + "]"));
        return options.filter((item, pos, self) => self.findIndex(v => v.id === item.id) === pos);
    }
    /** Supports Arrow up and down keys, Enter for selection
     * Escape is forwarded to owning component, so it may use it to close the dropdown.
     *
     * NB: Called by owning component to forward key event !!
     */
    export const onKeydown = (event: KeyboardEvent): void => {
        LOGGER.log("onKeydown: "+ event.key);
        let index = getOptions().findIndex(o => o.id === selectedOptionId);
        switch (event.keyCode) {
            case ARROW_DOWN: {
                index++;
                selectedOptionId = getOptions()[index].id;
                break;
            }
            case ARROW_UP: {
                index--;
                selectedOptionId = getOptions()[index].id;
                break;
            }
            case ENTER: {
                LOGGER.log("ENTER " + findOption(getOptions(), selectedOptionId).label)
                break;
            }
        }
    }

    /** Supports Arrow up and down keys, Enter for selection
     * Escape is forwarded to owning component, so it may use it to close the dropdown.
     *
     * NB: Called by owning component to forward key event !!
     */
    export const handleKeyDown = (e: KeyboardEvent): boolean => {
        const options = getOptions();
        const index = options.findIndex(o => o.id === selectedOptionId);
        LOGGER.log("handleKeyDown " + e.key + " index="+ index);
        switch (e.keyCode) {
            case ARROW_DOWN:
                if (index + 1 < options.length) {
                    setSelectedOption(options[index + 1].id);
                }
                return true;
            case ARROW_UP:
                if (index > 0) {
                    setSelectedOption(options[index - 1].id);
                }
                return true;
            case ENTER:
                if (index >= 0 && index < options.length) {
                    handleSelectedOption(options[index]);
                    // initOption();
                    return true;
                } else {
                    return false;
                }
            case DELETE:
                // handleSelectedOption(null);
                return true;
            case ESCAPE:
                // handleSelectedOption("ESCAPE");
                // initOption();
                return true;
        }
        return false;
    };

    const setSelectedOption = (index: string): void => {
        LOGGER.log("set selected option to "+ index);
        selectedOptionId = index;
    }

    const handleClickOutside = (event): void => {
        open = false;
    }

    const dispatcher = createEventDispatcher();
    const forward = (event: CustomEvent): void => {
        LOGGER.log("set selected SVELTE option to "+ event.detail.id);
        dispatcher("pi-ItemSelected", event.detail)
    }

</script>

<div class="dropdown"  on:keydown={onKeydown} >
    <div tabIndex={0}  />
    <div class="popupWrapper" use:clickOutside on:click_outside={handleClickOutside}>
        {#each getOptionsLogged() as option (option.id)}
            <div class="popup">
                <div>
                    <DropdownItemComponent on:pi-ItemSelected option={option} isSelected={option.id === selectedOptionId} />
                </div>
            </div>
        {/each}
    </div>
</div>

<style>
    .dropdown {
        position: relative;
    }

    .popup {
        position: relative;
        min-width: 60px;
        overflow-y: auto;
        overflow-x: auto;
        padding: 4px;

        z-index: 99;
        background: var(--pi-popup-background);
        border: 1px solid var(--pi-popup-border);
        box-shadow: var(--pi-popup-box-shadow);
        border-radius: 2px;
    }

    .popupWrapper {
        position: absolute;
        top: 10px;
        left: -1px;
    }
</style>
