// packages/core/src/editor/components/boxes/IndentComponent.tsx
import { observer } from "mobx-react";
import * as React from "react";

import { PiLogger, RENDER_LOG } from "../../../util/PiLogging";
import { IndentBox } from "../../boxes/IndentBox";
import { PiEditor } from "../../PiEditor";
import { RenderBox } from "../Rendering";

const LOGGER = new PiLogger("IndentComponent").mute();

export type IndentComponentProps = {
    box: IndentBox;
    editor: PiEditor;
};

@observer
export class IndentComponent extends React.Component<IndentComponentProps, {}> {

    indentStyle: object;

    constructor(props: IndentComponentProps) {
        super(props);
    }

    render() {
        RENDER_LOG.info(this, "Indent");
        const box = this.props.box;
        this.indentStyle = {
            marginLeft: "" + (this.props.box.indent * 8) + "px"
        };


        return (
            <div
                id={this.props.box.id}
                style={this.indentStyle}
                tabIndex={0}
            >
                <RenderBox key={this.props.box.child.id} box={this.props.box.child} editor={this.props.editor} />
            </div>
        );
    }
}

// packages/core-svelte/src/components/IndentComponent.svelte
<script lang="ts">
    import { autorun } from "mobx";
    import { FOCUS_LOGGER } from "./ChangeNotifier";
    import RenderComponent from "./RenderComponent.svelte";
    import type {IndentBox, PiEditor} from "@projectit/core";

    export let indentBox: IndentBox;
    export let editor: PiEditor;

    // style={{"marginLeft": indentBox.indent * 8 + "px" }}

    autorun( () => {
       indentBox.indent;
    });

    const onFocus = (e: FocusEvent) =>  {
        FOCUS_LOGGER.log("IndentComponent.onFocus")
    };
    const onBlur = (e: FocusEvent) => {
        FOCUS_LOGGER.log("IndentComponent.onBlur")
    }

</script>

<div
    class="indentStyle"
    tabIndex={0}
    on:focus={onFocus}
    on:blur={onBlur}
>
    <RenderComponent box={indentBox.child} editor={editor}/>
</div>

<style>
    .indentStyle {
        margin-left: 50px;
    }
</style>
