// packages/core-svelte/src/components/TextComponent.svelte
<svelte:options accessors={true} />

<script lang="ts">
    import { autorun } from "mobx";
    import {
        KEY_BACKSPACE,
        KEY_DELETE,
        KEY_ARROW_DOWN,
        KEY_ARROW_LEFT,
        KEY_ARROW_RIGHT,
        KEY_ARROW_UP,
        KEY_ENTER, KEY_SPACEBAR,
        KEY_TAB,
        EVENT_LOG,
        isMetaKey,
        KeyPressAction, PiUtils,
        TextBox,
        PiEditor,
        toPiKey,
        isAliasTextBox,
        PiCaret, PiCaretPosition, PiLogger, isPrintable, AliasBox, KEY_ESCAPE, styleToCSS, conceptStyle
    } from "@projectit/core";
    import { afterUpdate, onMount } from "svelte";
    import { AUTO_LOGGER, FOCUS_LOGGER, UPDATE_LOGGER } from "./ChangeNotifier";

    const LOGGER = new PiLogger("TextComponent");
    // Is this component currently being edited by the user?
    export let isEditing: boolean = false;
    export let textBox = new TextBox(null, "role:", () => "Editable textbox", (v: string) => {
    });
    export let editor: PiEditor;

    export let getText = (): string => {
        // TODO loopt eentje achter tijdens onKeyDown, want we kunnen de key nog negeren.
        return currentText();
    };

    export const setFocus = async () => {
        logBox("setFocus in setFocus");
        if (hasFocus()) {
            LOGGER.log("    has focus already");
            return;
        }
        element.focus();
        setCaretPosition(textBox.caretPosition);
    };

    function hasFocus(): boolean {
        return document.activeElement === element;
    }

    /**
     * Decides whether the default behavior of the event should be ignored
     * @param e
     */
    const shouldIgnore = (e: KeyboardEvent): boolean => {
        if (e.altKey) {
            return true;
        }
        return e.key === KEY_ENTER || e.key === KEY_TAB;
    };

    /**
     * Decides whether the  event should be propagated to the parent component
     * @param e
     */
    const shouldPropagate = (e: KeyboardEvent): boolean => {
        if (isPrintable(e)) {
            return true;
        }
        if (isMetaKey(e)) {
            if (e.key === KEY_ARROW_UP || e.key === KEY_ARROW_DOWN || e.key === KEY_TAB || e.key === KEY_SPACEBAR) {
                return true;
            }
        }
        if (e.key === KEY_ENTER || e.key === KEY_DELETE || e.key === KEY_TAB) {
            return true;
        }
        if (e.key === KEY_ARROW_UP || e.key === KEY_ARROW_DOWN || e.key === KEY_ESCAPE) {
            return true;
        }
        const caretPosition = getCaretPosition();
        if (e.key === KEY_ARROW_LEFT || e.key === KEY_BACKSPACE) {
            return caretPosition <= 0;
        } else if (e.key === KEY_ARROW_RIGHT || e.key === KEY_DELETE) {
            return caretPosition >= currentLength();
        } else {
            return false;
        }
    };

    function currentLength(): number {
        if (!!element && !!element.innerText) {
            return element.innerText.length;
        } else {
            return 0;
        }
    }

    function currentText(): string {
        if (!!element && !!element.innerText) {
            return element.innerText;
        } else {
            return "";
        }
    }

    let originalText: string;

    onMount(() => {
        LOGGER.log("onMount for role [" + textBox.role + "]");
        textBox.setFocus = setFocus;
        textBox.setCaret = setCaret;
        originalText = textBox.getText();
    });

    /**
     * Used to handle non-printing characters
     * @param event
     */
    const onKeyDown = async (event: KeyboardEvent) => {
        LOGGER.log("onKeyDown: [" + event.key + "] alt [" + event.ctrlKey + "] shift [" + event.shiftKey + "] key [" + event.key + "]");
        isEditing = true;
        if (event.key === KEY_DELETE) {
            if (currentText() === "") {
                if (textBox.deleteWhenEmptyAndErase) {
                    await editor.deleteBox(editor.selectedBox);
                    event.stopPropagation();
                    return;
                }
            }
            event.stopPropagation();
            return;
        }
        if (event.key === KEY_BACKSPACE) {
            if (currentText() === "") {
                if (textBox.deleteWhenEmptyAndErase) {
                    await editor.deleteBox(editor.selectedBox);
                    event.stopPropagation();
                    return;
                }
            }
        }
        if (!shouldPropagate(event)) {
            LOGGER.log("StopPropagation");
            event.stopPropagation();
        }
        if (shouldIgnore(event)) {
            event.preventDefault();
        }
        const piKey = toPiKey(event);
        if (isMetaKey(event) || event.key === KEY_ENTER) {
            const isKeyboardShortcutForThis = await PiUtils.handleKeyboardShortcut(piKey, textBox, editor);
            if (!isKeyboardShortcutForThis) {
                LOGGER.log("Key not handled for element " + textBox.element);
                if (event.key === KEY_ENTER) {
                    LOGGER.log("   ENTER, so propagate");
                    return;
                }
            }
        }
    };

    const setCaret = (caret: PiCaret) => {
        switch (caret.position) {
            case PiCaretPosition.RIGHT_MOST:
                LOGGER.log("setCaretPosition RIGHT");
                setCaretToMostRight();
                textBox.caretPosition = textBox.getText().length;
                break;
            case PiCaretPosition.LEFT_MOST:
                LOGGER.log("setCaretPosition LEFT");
                setCaretToMostLeft();
                textBox.caretPosition = 0;
                break;
            case PiCaretPosition.INDEX:
                LOGGER.log("setCaretPosition INDEX");
                setCaretPosition(caret.index);
                textBox.caretPosition = caret.index;
                break;
            case PiCaretPosition.UNSPECIFIED:
                LOGGER.log("setCaretPosition UNSPECIFIED");
                break;
            default:
                LOGGER.log("setCaretPosition ERROR");
                break;
        }
        logBox("setFocus in setCaret");
        // element.focus();
    };

    const setCaretToMostLeft = () => {
        setCaretPosition(0);
    };

    const setCaretToMostRight = () => {
        LOGGER.log("setCaretPosition RIGHT: " + textBox.getText().length);
        setCaretPosition(textBox.getText().length);
    };

    const setCaretPosition = (position: number) => {
        logBox("setCaretPosition: " + position);
        if (position === -1) {
            return;
        }
        try {
            if (position > currentLength()) {
                // TODO Fix the error below
                console.error("ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR; ");
                console.error("TextComponent.setCaretPosition position: " + position + " length: " + currentLength());
                position = currentLength();
            }
            clearSelection();
            const range = document.createRange();
            if (element!.childNodes[0]) {
                range.setStart(element!.childNodes[0], position);
            } else {
                range.setStart(element!, position);
            }
            range.collapse(true);
            window.getSelection().addRange(range);
            LOGGER.log("New position is: " + position);
            textBox.caretPosition = position;
        } catch (e) {
            console.error("TextComponent.setCaretPosition ERROR: " + e.toString());
        }
    };

    const clearSelection = () => {
        window.getSelection().removeAllRanges();
    };

    const onClick = async (event: MouseEvent) => {
        logBox("onClick before");
        textBox.caretPosition = getCaretPosition();
        logBox("onClick after");
    };

    function logBox(message: string) {
        LOGGER.log(message + ": box[" + textBox.role + ", " + textBox.caretPosition + "]");
    }

    /**
     * IS triggered for printable keys only,
     * @param event
     */
    const onKeyPress = async (event: KeyboardEvent) => {
        LOGGER.log("onKeyPress: " + event.key);
        isEditing = true;
        const insertionIndex = getCaretPosition();
        switch (textBox.keyPressAction(textBox.getText(), event.key, insertionIndex)) {
            case KeyPressAction.OK:
                logBox("KeyPressAction.OK");
                break;
            case KeyPressAction.NOT_OK:
                LOGGER.log("KeyPressAction.NOT_OK");
                event.preventDefault();
                event.stopPropagation();
                break;
            case KeyPressAction.GOTO_NEXT:
                LOGGER.log("KeyPressAction.GOTO_NEXT");
                editor.selectNextLeaf();
                LOGGER.log("    NEXT LEAF IS " + editor.selectedBox.role);
                if (isAliasTextBox(editor.selectedBox)) {
                    LOGGER.log("     is an alias box");
                    (editor.selectedBox.parent as AliasBox).triggerKeyPressEvent(event.key);
                } else {
                    LOGGER.log("     is NOT an alis box");
                }
                event.preventDefault();
                event.stopPropagation();
                break;
            case KeyPressAction.GOTO_PREVIOUS:
                LOGGER.log("KeyPressAction.GOTO_PREVIOUS");
                editor.selectPreviousLeaf();
                LOGGER.log("PREVIOUS LEAF IS " + editor.selectedBox.role);
                if (isAliasTextBox(editor.selectedBox)) {
                    (editor.selectedBox.parent as AliasBox).triggerKeyPressEvent(event.key);
                }
                event.preventDefault();
                event.stopPropagation();
                break;
        }
    };

    let text: string = textBox.getText();
    let element: HTMLDivElement;
    let placeholder: string;

    const onInput = async (e: InputEvent) => {
        isEditing = true;
        let value = currentText();
        console.log("onInput data" + e.data + ":  current [" + currentText() + "] box text [" + textBox.getText() + "]");
        textBox.caretPosition = getCaretPosition();
        textBox.setText(value);
        editor.selectedPosition = PiCaret.IndexPosition(textBox.caretPosition);
        if (textBox.deleteWhenEmpty && value.length === 0) {
            EVENT_LOG.info(this, "delete empty text");
            await editor.deleteBox(textBox);
        }
        LOGGER.log("END END text [" + currentText() + "]");
    };

    afterUpdate(() => {
        UPDATE_LOGGER.log("TextComponent update [" + isEditing + "] [" + currentText() + "] getText [" + textBox.getText() + "] text [" + text + "] box [" + textBox.role + "] caret [" + textBox.caretPosition + "]");
        textBox.setFocus = setFocus;
        textBox.setCaret = setCaret;
        // If being edited, do not set the value, let the user type whatever (s)he wants
        if (!isEditing) {
            text = textBox.getText();
        }
    });

    export const getCaretPosition = (): number => {
        // TODO This causes an extra afterUpdate in Svelte, don't know why !
        // return window.getSelection().focusOffset;
        return window.getSelection().getRangeAt(0).startOffset;
    };

    let textStyle: string = "";

    autorun(() => {
        AUTO_LOGGER.log("TextComponent role " + textBox.role + " text [" + text + "] current [" + currentText() + "] textBox [" + textBox.getText() + "] innertText [" + element?.innerText + "]");
        placeholder = textBox.placeHolder;
        // If being edited, do not set the value, let the user type whatever (s)he wants
        if (!isEditing) {
            text = textBox.getText();
        }
        // textStyle = ":before {" +  styleToCSS(conceptStyle(editor.style, "light", textBox.element.piLanguageConcept(), "text", textBox.style)) + "}";
        textStyle = styleToCSS(conceptStyle(editor.style, editor.theme, textBox.element.piLanguageConcept(), "text", textBox.style));

        textBox.setFocus = setFocus;
    });

    // const onFocus = async (e: FocusEvent) => {
    //     FOCUS_LOGGER.log("TextComponent.onFocus for box " + textBox.role);
    // };
    // const onBlurHandler = async (e: FocusEvent) => {
    //     FOCUS_LOGGER.log("TextComponent.onBlur for box " + textBox.role);
    // };

</script>

<span class={"text"}
      style="{textStyle}"
      tabindex="0"
      data-placeholdertext={placeholder}
      on:keypress={onKeyPress}
      on:keydown={onKeyDown}
      on:click={onClick}
      on:input={onInput}
      contenteditable="true"
      bind:innerHTML={text}
      bind:this={element}
></span>

<style>
    .text:empty:before {
        content: attr(data-placeholdertext);
        color: inherit;
        background-color: inherit;
        font-family: inherit;
        font-size: inherit;
        font-weight: inherit;
        padding: inherit;
        margin: inherit;
        display: inherit;
        white-space: inherit;
        border: inherit;
        opacity: 50%;
    }

    .text {
        background-color: var(--theme-colors-bg_text_box);
        content: attr(data-placeholdertext);
        color: var(--theme-colors-color_text_box);
        padding: 3px;
        white-space: normal;
        display: inline-block;
    }
</style>

// packages/core/src/editor/components/boxes/TextComponent.tsx
import * as classNames from "classnames";
import { observer } from "mobx-react";
import * as React from "react";

import { PiLogger } from "../../../util/PiLogging";
import { isAliasBox } from "../../boxes/AliasBox";
import { KeyPressAction, TextBox } from "../../boxes/TextBox";
import { PiEditor } from "../../PiEditor";
import { PiCaret, PiCaretPosition } from "../../../util/BehaviorUtils";
import * as Keys from "../../../util/Keys";
import { isMetaKey, reactToKey } from "../../../util/Keys";
import { EVENT_LOG, RENDER_LOG } from "../../../util/PiLogging";
import { PiUtils } from "../../../util/PiUtils";
import { STYLES } from "../styles/Styles";

const LOGGER = new PiLogger("TextComponent").mute();

export type TextComponentProps = {
    box: TextBox;
    editor: PiEditor;
};

@observer
export class TextComponent extends React.Component<TextComponentProps, {}> {
    originalValue: string = "";
    isEditing: boolean = false;
    private caretPosition: number = 0;
    private element: HTMLDivElement | null = null;
    private setElement = (element: HTMLDivElement | null) => {
        this.element = element;
    };

    constructor(props: TextComponentProps) {
        super(props);
        this.subscribeToBoxEvents(props.box);
    }

    componentWillReceiveProps(nextProps: TextComponentProps) {
        this.subscribeToBoxEvents(nextProps.box);
    }

    componentDidMount() {
        LOGGER.info(this, "componentDidMount");
        this.element!.setAttribute("contentEditable", "true");
        this.setCaretPosition(this.props.box.caretPosition);
        LOGGER.info(this, "componentDidMount caret: " + this.props.box.caretPosition);
        this.checkSelected();
    }

    componentDidUpdate() {
        LOGGER.info(this, "componentDidUpdate to [" + this.props.box.getText() + "]");
        LOGGER.info(this, "      caret [" + this.props.box.caretPosition + "]");
        // Ensure the selectable parent component calculates the new coordinates
        this.props.box.update();
        LOGGER.info(this, "      caret [" + this.props.box.caretPosition + "]");
        this.setCaretPosition(this.props.box.caretPosition);
        this.checkSelected();
    }

    protected checkSelected() {
        const selectedBox = this.props.editor.selectedBox;
        const isSelected = !!this.props.box && !!selectedBox ? this.props.box.id === selectedBox.id : false;
        if (isSelected) {
            LOGGER.info(this, "!!!!!!!!!!!!!!!!!!!!!!!!!! SELECTED position " + this.caretPosition);
            this.element.focus();
            this.setCaretPosition(this.caretPosition);
        } else {
            // LOGGER.info(this, "!!!!!!!!!!!!!!!!!!!!!!!!!! boxid " + this.props.box.id);
        }
    }

    render() {
        RENDER_LOG.info(this, "Text");
        const box = this.props.box;
        const styleClasses = classNames(STYLES.text, box.style);

        return (
            <div
                id={this.props.box.id}
                className={styleClasses}
                ref={this.setElement}
                tabIndex={0}
                onFocus={this.onFocus}
                onInput={this.onInput}
                onKeyDown={this.onKeyDown}
                onKeyPress={this.onKeyPress}
                onClick={this.onClick}
                onBlur={this.onBlur}
                data-placeholdertext={box.placeHolder}
                spellCheck={false}
                onPaste={this.onPaste}
            >
                {this.props.box.getText()}
            </div>
        );
    }

    private onFocus = () => {
        LOGGER.info(this, "onFocus: " + this.props.box.role + " : " + this.props.box.element.piId());
    };

    private onClick = () => {
        EVENT_LOG.info(this, "changeShowNavigator: " + this.props.box.getText());
        this.startEditing();
        this.props.box.caretPosition = this.getCaretPosition();
    };

    private onBlur = () => {
        EVENT_LOG.info(this, "onBlur: " + this.props.box.getText());
    };

    private onPaste = (e: React.SyntheticEvent<any>) => {
        EVENT_LOG.info(this, "onPaste: disabled pasting in text");
        e.stopPropagation();
        e.preventDefault();
        return false;
    };

    private onInput = async () => {
        const innerTextNotNull: string = this.element.innerText !== null ? this.element.innerText : "";

        EVENT_LOG.info(this, "onInput innerText [" + innerTextNotNull + "]");
        const box = this.props.box;
        box.caretPosition = this.getCaretPosition();
        this.caretPosition = box.caretPosition;
        this.props.editor.selectedPosition = PiCaret.IndexPosition(box.caretPosition);
        box.setText(innerTextNotNull);
        if (box.deleteWhenEmpty && box.getText().length === 0) {
            EVENT_LOG.info(this, "delete empty text");
            this.props.editor.deleteBox(box);
        }
        LOGGER.info(this, "END END");
        await this.props.editor.selectElement(box.element, box.role, this.props.editor.selectedPosition);
    };

    private onKeyDown = async (e: React.KeyboardEvent<any>) => {
        EVENT_LOG.info(this, "onKeyDown: key " + e.key + " keyCode " + e.keyCode + " charCode " + e.charCode + " isMeta?: " + isMetaKey(e));
        let handled: boolean = false;
        const caretPosition = this.getCaretPosition();
        if (e.keyCode === Keys.DELETE) {
            if (this.element.innerText === "") {
                if (this.props.box.deleteWhenEmptyAndErase) {
                    await this.props.editor.deleteBox(this.props.editor.selectedBox);
                    e.stopPropagation();
                    return;
                }
            }
            e.stopPropagation();
            return;
        }
        if (e.keyCode === Keys.BACKSPACE) {
            if (this.element.innerText === "") {
                if (this.props.box.deleteWhenEmptyAndErase) {
                    await this.props.editor.deleteBox(this.props.editor.selectedBox);
                    e.stopPropagation();
                    return;
                }
            }
        }
        if (!this.shouldPropagate(e)) {
            e.stopPropagation();
        }
        if (this.shouldIgnore(e)) {
            e.preventDefault();
        } else {
            // E.g. for all printable keys.
            handled = true;
        }
        const proKey = reactToKey(e);
        if (!handled && !isMetaKey(e)) {
            const isKeyboardShortcutForThis = await PiUtils.handleKeyboardShortcut(proKey, this.props.box, this.props.editor);
            if (!isKeyboardShortcutForThis) {
                EVENT_LOG.info(this, "Key not handled for element " + this.props.box.element);
                // Try the key on next box, if at the end of this box.
                const box = this.props.box;
                const insertionIndex = this.getCaretPosition();
                if (insertionIndex >= box.getText().length) {
                    this.props.editor.selectNextLeaf();
                    EVENT_LOG.info(this, "KeyDownAction NEXT LEAF IS " + this.props.editor.selectedBox.role);
                    if (isAliasBox(this.props.editor.selectedBox)) {
                        this.props.editor.selectedBox.triggerKeyDownEvent(proKey);
                    }
                    e.preventDefault();
                    e.stopPropagation();
                }
            }
        }
    };

    private onKeyPress = async (e: React.KeyboardEvent<any>) => {
        EVENT_LOG.info(this, "onKeyPress: " + e.key + "  " + this.props.box.actualWidth);
        const box = this.props.box;
        const insertionIndex = this.getCaretPosition();
        switch (this.props.box.keyPressAction(box.getText(), e.key, insertionIndex)) {
            case KeyPressAction.OK:
                EVENT_LOG.info(this, "KeyPressAction.OK");
                // box.setText(this.newText(box.getText(), insertionIndex, e.key));
                box.caretPosition = this.getCaretPosition() + 1;
                // e.preventDefault();
                e.stopPropagation();
                break;
            case KeyPressAction.NOT_OK:
                EVENT_LOG.info(this, "KeyPressAction.NOT_OK");
                e.preventDefault();
                e.stopPropagation();
                break;
            case KeyPressAction.GOTO_NEXT:
                EVENT_LOG.info(this, "KeyPressAction.GOTO_NEXT");
                this.props.editor.selectNextLeaf();
                EVENT_LOG.info(this, "NEXT LEAF IS " + this.props.editor.selectedBox.role);
                if (isAliasBox(this.props.editor.selectedBox)) {
                    this.props.editor.selectedBox.triggerKeyPressEvent(e.key);
                }
                e.preventDefault();
                e.stopPropagation();
                break;
        }
    };

    newText(text: string, index: number, char: string): string {
        return text.substring(0, index) + char + text.substring(index, text.length);
    }

    private setFocus = (): void => {
        LOGGER.info(this, "TextComponent set focus " + this.props.box.role);
        this.startEditing();
    };

    private subscribeToBoxEvents = (box: TextBox) => {
        box.setCaret = this.setCaret;
        box.setFocus = this.setFocus;
    };

    private setCaret = (caret: PiCaret) => {
        switch (caret.position) {
            case PiCaretPosition.RIGHT_MOST:
                LOGGER.info(this, "setCaretPosition RIGHT");
                this.setCaretToMostRight();
                break;
            case PiCaretPosition.LEFT_MOST:
                LOGGER.info(this, "setCaretPosition LEFT");
                this.setCaretToMostLeft();
                break;
            case PiCaretPosition.INDEX:
                LOGGER.info(this, "setCaretPosition INDEX");
                this.setCaretPosition(caret.index);
                break;
            case PiCaretPosition.UNSPECIFIED:
                LOGGER.info(this, "setCaretPosition UNSPECIFIED");
                break;
            default:
                LOGGER.info(this, "setCaretPosition ERROR");
                break;
        }
        this.element.focus();
    };

    private setCaretToMostLeft = () => {
        this.startEditing();
        this.setCaretPosition(0);
    };

    private setCaretToMostRight = () => {
        this.startEditing();
        LOGGER.info(this, "setCaretPosition RIGHT: " + this.props.box.getText().length);
        this.setCaretPosition(this.props.box.getText().length);
    };

    private shouldPropagate = (e: React.KeyboardEvent<any>): boolean => {
        if (isMetaKey(e)) {
            if (e.keyCode === Keys.ARROW_UP || e.keyCode === Keys.ARROW_DOWN || e.keyCode === Keys.TAB) {
                return true;
            }
        }
        if (e.keyCode === Keys.ENTER || e.keyCode === Keys.DELETE || e.keyCode === Keys.TAB) {
            return true;
        }
        if (e.keyCode === Keys.ARROW_UP || e.keyCode === Keys.ARROW_DOWN) {
            return true;
        }
        const caretPosition = this.getCaretPosition();
        if (e.keyCode === Keys.ARROW_LEFT || e.keyCode === Keys.BACKSPACE) {
            return caretPosition <= 0;
        } else if (e.keyCode === Keys.ARROW_RIGHT || e.keyCode === Keys.DELETE) {
            return caretPosition >= this.element.innerText.length;
        } else {
            return false;
        }
    };

    private shouldIgnore = (e: React.KeyboardEvent<any>): boolean => {
        if (e.altKey) {
            return true;
        }
        return e.keyCode === Keys.ENTER || e.keyCode === Keys.TAB;
    };

    startEditing = () => {
        if (this.isEditing) {
            return;
        }
        this.isEditing = true;
        this.originalValue = this.props.box.getText(); // this.text;

        // don't require extra click in FF
        if (this.element) {
            this.element.focus();
        }
    };

    stopEditing = (aborted?: boolean) => {
        this.isEditing = false;

        this.props.box.caretPosition = -1;
        if (aborted) {
            this.props.box.setText(this.originalValue);
        }
        this.clearSelection();
    };

    private getCaretPosition = (): number => {
        return window.getSelection().focusOffset;
    };

    private setCaretPosition = (position: number) => {
        if (position === -1) {
            return;
        }
        if (!this.element.innerText) {
            // TODO Find out why innertext can be falsy.
            return;
        }
        try {
            if (position > this.element.innerText.length) {
                // TODO Fix the error below
                console.log("ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR; ");
                console.log("TExtComponent.setCaretPosition >length: " + position + " > " + this.element.innerText.length);
                // position = this.element.innerText.length;
            }
            this.clearSelection();
            const range = document.createRange();
            if (this.element!.childNodes[0]) {
                range.setStart(this.element!.childNodes[0], position);
            } else {
                range.setStart(this.element!, position);
            }
            range.collapse(true);
            window.getSelection().addRange(range);
            this.caretPosition = position;
            this.props.box.caretPosition = position;
        } catch (e) {
            console.log("TextComponent.setCaretPosition ERROR: " + e.toString());
        }
    };

    private clearSelection = () => {
        window.getSelection().removeAllRanges();
    };
}
