// packages/core-svelte/src/components/SelectableComponent.svelte
<script lang="ts">
    import {
        Box,
        LabelBox,
        PiEditor,
        PiLogger
    } from "@projectit/core";
    import { autorun } from "mobx";
    import { afterUpdate, tick } from "svelte";
    import { AUTO_LOGGER } from "./ChangeNotifier";

    // Parameters
    export let box: Box = new LabelBox(null, "DUMMY", "LABEL");
    export let editor: PiEditor ;

    let LOGGER = new PiLogger("SelectableComponent");
    let isSelected: boolean = false;
    let className: string;
    let element: HTMLDivElement = null;

    const onClick = (event: MouseEvent) => {
        LOGGER.log("SelectableComponent.onClick: "+ event + " for box " + box.role);
        isSelected = !isSelected;

        if (box.selectable) {
            LOGGER.log("       ===> selected box " + box.role);
            editor.selectedBox = box;
            event.preventDefault();
            event.stopPropagation();
        }

    };

    afterUpdate ( async () => {
        LOGGER.log("!!!!! SelectableComponent.afterupdate, box="+ box);
        // await tick();
        if(element === null){
            return;
        }
        const rect: ClientRect = element.getBoundingClientRect();
        if(box !== null){
            box.actualX = rect.left;
            box.actualY = rect.top;
            box.actualHeight = rect.height;
            box.actualWidth = rect.width;
            LOGGER.log("   actual is "+ box.actualWidth)
        }
    });

    autorun( () => {
        LOGGER.log("AUITORYN SelectableComponent for box: " + box.role)
        isSelected = editor.selectedBox === box;
        className = (isSelected ? "selectedComponent" : "unSelectedComponent");
    })
</script>

<!-- NOTE The clientHeight binding is here to ensure that the afterUpdate is fired.
     If it isn't there, afterUpdate will never be fired.
-->
<div class={className}
     tabIndex={0}
     on:click={onClick}

     bind:clientHeight={box.actualHeight}
     bind:this={element} >
    <slot class="slot" editor={editor}/>
</div>

<style>
    .slot {
        display: inline;
    }
    .unSelectedComponent {
        background: transparent;
        border: none;
        display: inline-block;
        vertical-align: middle;
    }

    .selectedComponent {
        height: 100%;
        background-color: var(--pi-selected-background-color);
        border: 1px solid darkblue;
        display: inline-block;
        vertical-align: middle;
        border-radius: 3px;
    }
</style>

// packages/core/src/components/SelectableComponent.tsx
import { observer } from "mobx-react";
import * as React from "react";

import { PiUtils } from "../util/PiUtils";
import { reactToKey } from "../util/Keys";
import { isAliasBox } from "../boxes/AliasBox";
import { isSelectBox } from "../boxes/SelectBox";
import { isTextBox } from "../boxes/TextBox";
import { EVENT_LOG } from "../util/PiLogging";
import { STYLES } from "./styles/Styles";
import { Box } from "../boxes/Box";
import { PiEditor } from "../editor/PiEditor";
import { wait } from "../util/PiUtils";

export type SelectableComponentProps = {
  box: Box;
  editor: PiEditor;
};

/**
 * Wrapper for each component, to ansure each component is selectable.
 */
@observer
export class SelectableComponent extends React.Component<
  SelectableComponentProps,
  {}
> {
  private element: HTMLDivElement;
  private setElement = (element: HTMLDivElement | null) => {
    if (element) {
      this.element = element;
    }
  };

  constructor(props: SelectableComponentProps) {
    super(props);
    this.componentDidUpdate = this.componentDidUpdate.bind(this);
  }

  async componentDidMount() {
    EVENT_LOG.info(this, "componentDidMount");
    await this.updateViewStateAfterRender();
  }

  async componentDidUpdate() {
    await this.updateViewStateAfterRender();
  }

  render() {
    const selectedBox = this.props.editor.selectedBox;
    let style: string;
    let isSelected =
      !!this.props.box && !!selectedBox
        ? this.props.box.id === selectedBox.id
        : false;
    if (isSelected) {
      if (
        isTextBox(selectedBox) ||
        isAliasBox(selectedBox) ||
        isSelectBox(selectedBox)
      ) {
        style = STYLES.selectedTextComponent;
      } else {
        style = STYLES.selectedComponent;
      }
    } else {
      style = STYLES.unSelectedComponent;
    }
    // Ensure that am Alias- or TextComponent can call the uodate nmethod, because this selectable
    // component won;t be rendered.
    if (
      isTextBox(this.props.box) ||
      isAliasBox(this.props.box) ||
      isSelectBox(this.props.box)
    ) {
      this.props.box.update = this.componentDidUpdate;
    }
    return (
      <div
        className={style}
        tabIndex={0}
        onClick={this.onClick}
        onKeyDown={this.onKeyDown}
        ref={this.setElement}
      >
        {this.props.children}
      </div>
    );
  }

  onKeyDown = (e: React.KeyboardEvent<any>) => {
    EVENT_LOG.info(this, "onKeyDown");
    if (
      PiUtils.handleKeyboardShortcut(
        reactToKey(e),
        this.props.box,
        this.props.editor
      )
    ) {
      e.preventDefault();
      e.stopPropagation();
    }
  };

  private onClick = (event: React.MouseEvent<HTMLDivElement>) => {
    EVENT_LOG.info(
      this,
      "===> onClick (" +
        this.props.box.actualX +
        ", " +
        this.props.box.actualY +
        ") width " +
        this.props.box.actualWidth
    );
    if (this.props.box.selectable) {
      EVENT_LOG.info(this, "===> selected box " + this.props.box.role);
      this.props.editor.selectedBox = this.props.box;
      event.preventDefault();
      event.stopPropagation();
    }
  };

  /**
   * Update the actual coordinates of the component.
   * Used for (semi) graphic contents like lines.
   * @returns {Promise<void>}
   */
  private async updateViewStateAfterRender(): Promise<void> {
    await wait(0);
    if (this.element) {
      const box = this.props.box;
      const rect: ClientRect = this.element.getBoundingClientRect();

      box.actualX = rect.left;
      box.actualY = rect.top;
      box.actualHeight = rect.height;
      box.actualWidth = rect.width;
    }
  }
}
